
# ec2.yml 
--- 
- name: Launch two EC2 instances 
  hosts: localhost 
  connection: local 
  gather_facts: no 
  vars: 
    aws_region: us-east-1 
    instance_type: t2.micro 
    key_name: my-ansible-key 
    security_group: my-ansible-sg 
    image_id: ami-0360c520857e3138f  # Update id  
  tasks: 
    - name: Create key pair 
      amazon.aws.ec2_key: 
        name: "{{ key_name }}" 
        region: "{{ aws_region }}" 
        state: present 
      register: keypair 
 
    - name: Save private key locally 
      copy: 
        content: "{{ keypair.key.private_key }}" 
        dest: "~/.ssh/{{ key_name }}.pem" 
        mode: '0600' 
      when: keypair.changed 
 
    - name: Create security group 
      amazon.aws.ec2_security_group: 
        name: "{{ security_group }}" 
        description: "Allow SSH and HTTP" 
        region: "{{ aws_region }}" 
        rules: 
          - proto: tcp 
            from_port: 22 
            to_port: 22 
            cidr_ip: 0.0.0.0/0 
          - proto: tcp 
            from_port: 80 
            to_port: 80 
            cidr_ip: 0.0.0.0/0 
        rules_egress: 
          - proto: -1 
            from_port: 0 
            to_port: 0 
            cidr_ip: 0.0.0.0/0 
 
    - name: Launch EC2 instances 
      amazon.aws.ec2_instance: 
        name: "ansible-demo" 
        key_name: "{{ key_name }}" 
        instance_type: "{{ instance_type }}" 
        image_id: "{{ image_id }}" 
        region: "{{ aws_region }}" 
        count: 2 
        wait: yes 
        security_group: "{{ security_group }}" 
      register: ec2 
 
    - name: Show public IPs 
      debug: 
        var: ec2.instances | map(attribute='public_ip_address') | list 
