--- 
- name: Create an S3 bucket 
  hosts: localhost 
  connection: local 
  gather_facts: no 
  vars: 
    aws_region: us-east-1 
    bucket_name: s3-nonpdemo-ansible-demo-bucket-2025   # must be globally unique 
  tasks: 
    - name: Create S3 bucket 
      amazon.aws.s3_bucket: 
        name: "{{ bucket_name }}" 
        state: present 
        region: "{{ aws_region }}" 
      register: s3_result 
 
    - name: Show bucket creation result 
      debug: 
        var: s3_result 
